project:
  type: website
  output-dir: docs

website:
  title: "In the Details"
  navbar:
    right:
      - icon: github
        href: https://github.com/zajichek/inthedetails
format:
  html:
    theme:
      - lux
    css: styles.css



